GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

STRINGS.ACTIONS.CASTAOE.GYC_MB3 = "蓄力攻击"

STRINGS.CHARACTER_TITLES.bcj = "白川玖"
STRINGS.CHARACTER_NAMES.bcj = "白川玖"
STRINGS.CHARACTER_DESCRIPTIONS.bcj = "*人死不能复生\n*下葬不必挖坟\n*教科书级的反面案例\n*你是我见过最烂的兽医"
STRINGS.CHARACTER_QUOTES.bcj = "\"要医术有医术，要素质有医术。\""
STRINGS.CHARACTER_SURVIVABILITY.bcj = "微死"
STRINGS.SKIN_NAMES.bcj_none = "白川玖" 
STRINGS.SKIN_NAMES.bcj_skin1_none = "白川玖" 

STRINGS.CHARACTER_TITLES.gyc = "古宇辰"
STRINGS.CHARACTER_NAMES.gyc = "古宇辰"
STRINGS.CHARACTER_DESCRIPTIONS.gyc = "*符箓销冠\n*坑蒙拐骗一把手\n*天桥算命扛把子\n*殡葬行业精英从业人员\n*弱小可怜又无助但特别能打"
STRINGS.CHARACTER_QUOTES.gyc = "\"道袍上有阴阳太极印文。\""
STRINGS.CHARACTER_SURVIVABILITY.gyc = "如活"
STRINGS.SKIN_NAMES.gyc_none = "古宇辰" 
STRINGS.SKIN_NAMES.gyc_skin1_none = "古宇辰" 

STRINGS.CHARACTERS.BCJ = require "speech_bcj"
STRINGS.CHARACTERS.GYC = require "speech_gyc"

STRINGS.NAMES.BCJ_GLASS = "金丝眼镜" 
STRINGS.RECIPE_DESC.BCJ_GLASS = "朴实无华的金丝眼镜" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_GLASS = "戴上后看起来很聪明。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_GLASS = "优雅，永不过时"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_GLASS = "戴上后也只有看起来聪明" 

STRINGS.NAMES.BCJ_444_1 = "444" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_444_1 = "一个会动的黑米团子。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_444_1 = "我没有办法和你解释，因为444只是一只小猫咪"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_444_1 = "来，喵一个。" 

STRINGS.NAMES.BCJ_444_2 = "444" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_444_2 = "一个会动的黑米团子。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_444_2 = "我没有办法和你解释，因为444只是一只小猫咪"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_444_2 = "来，喵一个。" 

STRINGS.NAMES.BCJ_444_3 = "444" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_444_3 = "一个会动的黑米团子。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_444_3 = "我没有办法和你解释，因为444只是一只小猫咪"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_444_3 = "来，喵一个。" 

STRINGS.NAMES.BCJ_444_4 = "444" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_444_4 = "一个会动的黑米团子。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_444_4 = "我没有办法和你解释，因为444只是一只小猫咪"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_444_4 = "来，喵一个。" 

STRINGS.NAMES.BCJ_444_5 = "444" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_444_5 = "一个会动的黑米团子。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_444_5 = "我没有办法和你解释，因为444只是一只小猫咪"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_444_5 = "来，喵一个。" 

STRINGS.NAMES.BCJ_GUN = "白日梦" 
STRINGS.RECIPE_DESC.BCJ_GUN = "贴符手枪" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_GUN = "看起来看和燧发枪不太一样。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_SWORD1 = "朋友，时代变了！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SWORD1 = "不愧是我亲手贴的符，帅！" 

STRINGS.NAMES.BCJ_SWORD1 = "挚友亲朋" 
STRINGS.RECIPE_DESC.BCJ_SWORD1 = "这可是我的挚友亲朋" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_SWORD1 = "这可是她的挚友亲朋。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_SWORD1 = "这可是我的挚友亲朋。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SWORD1 = "啊？这是我吗？" 

STRINGS.NAMES.BCJ_SWORD2 = "得加钱"
STRINGS.RECIPE_DESC.BCJ_SWORD2 = "得加钱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_SWORD2 = "得加钱." 
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_SWORD2 = "加个屁。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SWORD2 = "得加钱." 

STRINGS.NAMES.BCJ_SWORD3 = "狂想曲"
STRINGS.RECIPE_DESC.BCJ_SWORD3 = "加钱了" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_SWORD3 = "有一种不祥的预感..." 
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_SWORD3 = "金钱是社畜的补品，大补！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SWORD3 = "加你自己的钱啊！我的钱包呜呜呜！" 

STRINGS.NAMES.BCJ_SAN1 = "骨伞" 
STRINGS.RECIPE_DESC.BCJ_SAN1 = "一把骨头做成的伞" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_SAN1 = "一把阴气森森的伞。" 
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_SAN1 = "前辈加加油啊！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SAN1 = "怎么会有人用骨头做法器啊（指指点点）" 

STRINGS.NAMES.BCJ_SAN2 = "鬼伞" 
STRINGS.RECIPE_DESC.BCJ_SAN2 = "一把充满怨气的伞"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_SAN2 = "一把鬼气森森的伞。" 
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_SAN2 = "比你的前辈好用些~"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SAN2 = "你的人皇伞怎么冒黑烟啊?" 

STRINGS.NAMES.BCJ_SAN3 = "安魂曲" 
STRINGS.RECIPE_DESC.BCJ_SAN3 = "好梦......" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_SAN3 = "zzz……" 
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_SAN3 = "星辰不见太阳光，永眠长逝莫悲伤，虚空极尽莫能计，每在心旁总情长，人随水去泪汪汪，心力点点酒苍茫，还记十月相倚伴，谁人犹在我他旁。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_SAN3 = "生死无悔全为有你" 

STRINGS.NAMES.BCJ_CL1 = "骨灰坛子" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL1 = "充满着不详的感觉" 
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL1 = "洗洗还能用。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL1 = "混点草木灰会被发现吗？" 

STRINGS.NAMES.BCJ_CL1_FULL = "装着骨架的坛子" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL1_FULL = "充满着不详的感觉" 
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL1_FULL = "洗洗还能用悲伤。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL1_FULL = "混点草木灰会被发现吗？" 

STRINGS.NAMES.BCJ_CL2 = "槐花" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL2 = "香香的"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL2 = "白白的。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL2 = "甜甜的" 

STRINGS.NAMES.BCJ_CL3 = "老槐树皮" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL3 = "一块干巴巴的树皮。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL3 = "干干巴巴的，麻麻赖赖的，一点都不圆润。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL3 = "充满阴气的制符材料，可以做点好玩的。"

STRINGS.NAMES.BCJ_CL4 = "雷击木" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL4 = "烧焦的木头."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL4 = "。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL4 = "生死无悔全为有你"

STRINGS.NAMES.BCJ_CL5 = "面粉"
STRINGS.RECIPE_DESC.BCJ_CL5 = "面粉" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL5 = "可以做出很多面食"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL5 = "星辰不见太阳光，永眠长逝莫悲伤，虚空极尽莫能计，每在心旁总情长，人随水去泪汪汪，心力点点酒苍茫，还记十月相倚伴，谁人犹在我他旁。"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_CL5 = "面条，包子，花卷，煎饼，油条......"

STRINGS.NAMES.BCJ_CL6 = "桃花" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL6 = "很漂亮的粉色花花"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL6 = "桃之夭夭，灼灼其华"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL6 = "桃花树下桃花庵，桃花庵下桃花仙" 

STRINGS.NAMES.BCJ_CL7 = "桃木枝" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL7 = "桃木枝."

STRINGS.NAMES.BCJ_CL8 = "桃子" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL8 = "很好吃的水果"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL8 = "白里透着红啊，是红里透……啊！你打我干嘛！"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_CL8 = "好吃，爱吃，多吃"

STRINGS.NAMES.BCJ_CL9 = "天选桃木枝" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL9 = "天选桃木枝."

STRINGS.NAMES.BCJ_CL10 = "小麦" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL10 = "春种一棵草."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL10 = "春种一棵草"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL10 = "建议粉身碎骨，过刀山，下油锅。" 

STRINGS.NAMES.BCJ_CL11 = "朱砂" 
STRINGS.RECIPE_DESC.BCJ_CL11 = "绘制符纸的必备道具" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CL11 = "应该是红色的矿物，但是有股血腥味."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CL11 = "喔~红红的喔~"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CL11 = "是血做的吗，如是" 

STRINGS.NAMES.BCJ_FOOD1 = "AD钙奶" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD1 = "酸酸甜甜的小饮料" 
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD1 = "童年的味道我知道"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD1 = "我能一口气喝一排！" 

STRINGS.NAMES.BCJ_FOOD2 = "河北正宗安徽牛肉板面" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD2 = "好吃的面条"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD2 = "新疆人在东北大学食堂吃到了四川人做的河北正宗安徽牛肉板面"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD2 = "加点辣椒更好吃" 

STRINGS.NAMES.BCJ_FOOD3 = "槐花饭" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD3 = "到底是给谁吃的饭？."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD3 = "量大管饱，你问给谁吃的？你问题怎么这么多？"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD3 = "饭堆到冒尖，插上筷子。。。。。。" 

STRINGS.NAMES.BCJ_FOOD4 = "牡丹糕" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD4 = "牡丹糕，但是野花花瓣"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD4 = "牡丹糕里没牡丹，就像老婆饼里没有老婆"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD4 = "牡丹糕，但是野花花瓣" 

STRINGS.NAMES.BCJ_FOOD5 = "奇怪的料理" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD5 = "黑乎乎的一坨，看起来完全没有食欲."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD5 = "牡丹糕里没牡丹，就像老婆饼里没有老婆"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD5 = "牡丹糕，但是野花花瓣" 

STRINGS.NAMES.BCJ_FOOD6 = "圣女果炒鹌鹑蛋" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD6 = "奇奇怪怪的菜肴."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD6 = "难想象是在什么样的精神状态下做出的这道菜"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD6 = "怎么不算红白之物呢" 

STRINGS.NAMES.BCJ_FOOD7 = "桃花酒" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD7 = "感觉度数不高，但是后劲很足"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD7 = "喝了变成玛卡巴卡"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD7 = "酒壮怂人胆" 

STRINGS.NAMES.BCJ_FOOD8 = "桃花酿" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD8 = "带有酒味的甜点"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD8 = "按理说这个东西不该塞进嘴里，但我不讲道理"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD8 = "味道还行的酒酿，不建议多吃，不然我就没酒了" 

STRINGS.NAMES.BCJ_FOOD9 = "桃花酥" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD9 = "很精致的点心，让人舍不得吃."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD9 = "春风十里不如吃你"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD9 = "层层叠叠，酥脆可口" 

STRINGS.NAMES.BCJ_FOOD10 = "西瓜炒肉" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD10 = "神奇的味道。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD10 = "你的食堂，我的食堂，大家都一样"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD10 = "食堂的创新，让人眼前一黑再一黑" 

STRINGS.NAMES.BCJ_FOOD11 = "小熊软糖" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD11 = "没有人不喜欢小熊软糖"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD11 = "500g卖我十块钱，奸商！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD11 = "看，是野生的小熊软糖" 

STRINGS.NAMES.BCJ_FOOD12 = "蒸槐花" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FOOD12 = "没味儿，但我喜欢."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FOOD12 = "牡丹糕里没牡丹，就像老婆饼里没有老婆"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FOOD12 = "牡丹糕，但是野花花瓣"

STRINGS.NAMES.BCJ_FU1 = "回春符"  
STRINGS.RECIPE_DESC.BCJ_FU1 = "可以治疗伤势的符纸" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FU1 = "可以治疗伤势的符纸"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FU1 = "喔~绿绿的喔~"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FU1 = "致命伤，但还能救" 

STRINGS.NAMES.BCJ_FU2 = "金甲符" 
STRINGS.RECIPE_DESC.BCJ_FU2 = "能抵御一定伤害的符纸" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FU2 = "意外好用的防御道具"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FU2 = "喔~硬硬的喔~"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FU2 = "我的金钟罩铁布衫毫无破绽" 

STRINGS.NAMES.BCJ_FU3 = "明光符" 
STRINGS.RECIPE_DESC.BCJ_FU3 = "可以治疗伤势的符纸" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FU3 = "可以治疗伤势的符纸"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FU3 = "喔~绿绿的喔~"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FU3 = "致命伤，但还能救" 

STRINGS.NAMES.BCJ_FU4 = "五雷符" 
STRINGS.RECIPE_DESC.BCJ_FU4 = "拥有巨大力量的符纸" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FU4 = "轰轰轰轰轰"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FU4 = "九天玄刹，化为神雷，煌煌天威，以剑引之。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FU4 = "喔~痛痛的喔~" 

STRINGS.NAMES.BCJ_FU5 = "招阴符" 
STRINGS.RECIPE_DESC.BCJ_FU5 = "拥有奇奇怪怪作用的符纸" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_FU5 = "很危险的符纸，建议慎用"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_FU5 = "喔~爽爽的喔~"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_FU5 = "全场影怪向我看齐，我宣布个事" 

STRINGS.NAMES.GYC_HAT = "天师帽" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_HAT = "是仪式服装吗？"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_HAT = "戴上这个她好像老了十岁不止"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_HAT = "师父试图焊我头上的帽子" 

STRINGS.NAMES.GYC_MB1 = "毛笔" 
STRINGS.RECIPE_DESC.GYC_MB1 = "一支有点秃的笔。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_MB1 = "这东西还能写字吗？"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_MB1 = "家传法器，从未维修，画符成功率高达百分之一"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_MB1 = "一般情况下我不会碰这支笔" 

STRINGS.NAMES.GYC_MB2 = "桃木笔" 
STRINGS.RECIPE_DESC.GYC_MB2 = "一支正常的笔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_MB2 = "看起来很好写字的笔"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_MB2 = "拿起它，耳边好像有古宇辰在说：狗爬的字哈哈"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_MB2 = "修一下用着顺手多了" 

STRINGS.NAMES.GYC_MB3 = "古宇辰的毛笔" 
STRINGS.RECIPE_DESC.GYC_MB3 = "超级华丽的笔。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_MB3 = "看起来很贵的笔"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_MB2 = "但是话又说回来，也不是不能拿"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_MB2 = "指哪打哪，华而有实" 

STRINGS.NAMES.GYC_TMJ1 = "天选桃木枝" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_TMJ1 = "一根很直的树枝"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_TMJ2 = "没有人能拒绝这样一根树枝，可惜，我不是人"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_TMJ2 = "感谢大自然的馈赠" 

STRINGS.NAMES.GYC_TMJ2 = "桃木剑" 
STRINGS.RECIPE_DESC.GYC_TMJ2 = "用桃木雕刻成的剑。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_TMJ2 = "像是过家家的玩具木剑..."  
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_TMJ2 = "一般情况下我不喜欢这个"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_TMJ2 = "别再问木剑怎么开刃，我们道士杀人一般不见血" 

STRINGS.NAMES.GYC_TMJ3 = "降妖剑" 
STRINGS.RECIPE_DESC.GYC_TMJ3 = "有生命的剑。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_TMJ3 = "为什么剑上会开花？"  
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_TMJ3 = "但是话又说回来"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_TMJ3 = "脱离了低级趣味，试图开花的剑" 

STRINGS.NAMES.GYC_TMJ4 = "诛邪剑" 
STRINGS.RECIPE_DESC.GYC_TMJ4 = "周边被不知名金属包裹的剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_TMJ4 = "既有生命的美丽，也有金属的锋利"  
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_TMJ4 = "我依旧不喜欢这个"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_TMJ4 = "看起来能杀了你，实际上能杀你全家" 

STRINGS.NAMES.GYC_TMJ5 = "古宇辰的剑" 
STRINGS.RECIPE_DESC.GYC_TMJ5 = "利刃。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_TMJ5 = "看起来能把我杀了"  
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_TMJ4 = "长矛沾屎戳谁谁死"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_TMJ4 = "完全炼化，行随心动" 

STRINGS.NAMES.BCJ_TAOS = "桃树" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_TAOS = "这棵树被照顾的很好"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_TAOS = "桃，五木之精，仙木也."
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_TAOS = "种树，摘花，吃果果"

STRINGS.NAMES.BCJ_TAOS_BURNT = "焦黑的桃木干" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_TAOS_BURNT = "黑不溜秋的木头."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_TAOS_BURNT = "人这一生，挨批很正常，树也一样."
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_TAOS_BURNT = "又有倒霉蛋被雷劈了？" 

STRINGS.NAMES.BCJ_GHOST_SOUL = "鬼火" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_GHOST_SOUL = "好像在说话。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_GHOST_SOUL = "吃了吗？没吃吃我一铲。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_GHOST_SOUL = "主要提供一个坟地的氛围感"

STRINGS.NAMES.DUG_BCJ_LHS = "老槐树的根" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BCJ_LHS = "皱巴巴的根，不知道是什么植物的。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.DUG_BCJ_LHS = "按道上的说法，这是家的雏形。"
STRINGS.CHARACTERS.GYC.DESCRIBE.DUG_BCJ_LHS = "到底死没死，如死。"

STRINGS.NAMES.BCJ_LHS = "老槐树" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_LHS = "站在下面感觉阴森森的"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_LHS = "槐之木，鬼之居也"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_LHS = "到底活没活？如活。"

STRINGS.NAMES.BCJ_LHS_BIG = "老槐树_超大" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_LHS_BIG = "站在下面感觉阴森森的"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_LHS_BIG = "槐之木，鬼之居也"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_LHS_BIG = "到底活没活？如活。"

STRINGS.NAMES.BCJ_JIANZHU1 = "坛子" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU1 = "洗洗还能用" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU1 = "哦~凉凉的喔~"

STRINGS.NAMES.BCJ_JIANZHU3 = "AD钙奶套装" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU3 = "白川玖喜欢在坐在天台的马扎上，一边吹风一边喝一整排AD钙奶，她说这是一种情趣，啊不对，一种兴趣。" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU3 = "如果是在天台那就更好了。"

STRINGS.NAMES.BCJ_JIANZHU4 = "鬼火灯"
STRINGS.RECIPE_DESC.BCJ_JIANZHU4 = "除了好看一无是处"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU4 = "那只手是哪里来的？"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU4 = "提灯确实需要被手提更有感觉。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU4 = "只手，主要起到一个造型的作用。"

STRINGS.NAMES.BCJ_JIANZHU6 = "磷火堆"
STRINGS.RECIPE_DESC.BCJ_JIANZHU6 = "除了更贵一无是处"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU6 = "我的手好像能穿过堆火。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU6 = "我的手好像能穿过堆火。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU6 = "我的手好像能穿过堆火。"

STRINGS.NAMES.BCJ_JIANZHU8 = "蒲团" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU8 = "圆圆的蒲团，看起来很软很舒服" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU8 = "看起来很软很舒服."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU8 = "坐在上面的时候觉得像屁股下扎了根针."
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU8 = "今日无事，蒲团打坐" 

STRINGS.NAMES.BCJ_JIANZHU9 = "桃木灵牌"
STRINGS.RECIPE_DESC.BCJ_JIANZHU9 = "用桃木制作的灵位"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU9 = "虽然是灵位，但是充满正气"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU9 = "又多了一个家，欸嘿"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU9 = "至阳之木做至阴之物，我是天才" 

STRINGS.NAMES.BCJ_JIANZHU10 = "替身木偶" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU10 = "价值一复活币" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU10 = "造型奇怪的木偶"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU10 = "做人没必要太正常，做替身也是"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU10 = "替身还是替死" 

STRINGS.NAMES.BCJ_JIANZHU11 = "香案"
STRINGS.RECIPE_DESC.BCJ_JIANZHU11 = "一个四四方方的桌子"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU11 = "感觉是很实用的家具"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU11 = "太可拷了。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU11 = "祖师爷未来的住所。" 

STRINGS.NAMES.BCJ_JIANZHU12 = "小马扎" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU12 = "普普通通的马扎" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU12 = "坐起来很舒服"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU12 = "十分怀念我的AD钙奶."
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU12 = "很适合坐着乘凉" 

STRINGS.NAMES.BCJ_JIANZHU13 = "纸扎人" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU13 = "非常粗糙的，扭曲的，阴暗的“纸人”" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU13 = "我的手艺简直绝了~"

STRINGS.NAMES.BCJ_JIANZHU14 = "祖师爷的雕像" 
STRINGS.RECIPE_DESC.BCJ_JIANZHU14 = "突然出现的奇怪雕像" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_JIANZHU14 = "应该放在香案上供起来"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_JIANZHU14 = "应该放在香案上供起来！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_JIANZHU14 = "应该放在香案上供起来" 

STRINGS.NAMES.BCJ_TABLE = "白川玖的贡桌" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_TABLE = "像是恐怖故事里的灵位。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_TABLE = "首先，出发点是好的；其次，先别出发。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_TABLE = "一定要把蜡烛亮成蓝色吗？"

STRINGS.NAMES.GYC_TABLE = "祖师爷的贡桌" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_TABLE = "看起来让人很安心。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_TABLE = "隔行如隔山，我祝你成功吧。。"
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_TABLE = "香火不能断，贡品不能少。"

STRINGS.NAMES.BCJ_ITEM1 = "龟壳" 
STRINGS.RECIPE_DESC.BCJ_ITEM1 = "一个刻着字的龟壳" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_ITEM1 = "感觉神神叨叨的"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_ITEM1 = "我是小孩子，不是大傻子！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_ITEM1 = "我可会算命了，包不准的！" 

STRINGS.NAMES.BCJ_ITEM2 = "绝望" 
STRINGS.RECIPE_DESC.BCJ_ITEM2 = "爱……" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_ITEM2 = "很不好的感觉。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_ITEM2 = "我躲在名为爱的囚笼……"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_ITEM2 = "我躲在名为爱的囚笼……" 

STRINGS.NAMES.BCJ_ITEM3 = "希望" 
STRINGS.RECIPE_DESC.BCJ_ITEM3 = "死亡……" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_ITEM3 = "可以穿透空间的道具"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_ITEM3 = "丧钟为谁而鸣？"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_ITEM3 = "丧钟为你而鸣。" 

STRINGS.NAMES.BCJ_ITEM4 = "祖师爷的道袍"
STRINGS.RECIPE_DESC.BCJ_ITEM4 = "一件普通的道袍"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_ITEM4 = "祖师爷的道袍."
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_ITEM4 = "没有人能拒绝一件永远不会脏的道袍。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_ITEM4 = "祖师爷的道袍." 

STRINGS.NAMES.BCJ_ITEM5 = "白川玖的白大褂"
STRINGS.RECIPE_DESC.BCJ_ITEM5 = "一件普通的白大褂"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_ITEM5 = "一件平平无奇的白大褂"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_ITEM5 = "没有人能拒绝一件永远不会脏的白大褂。"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_ITEM5 = "是医生吗？如是。" 

STRINGS.NAMES.BCJ_CD2 = "疯狂画家"
STRINGS.RECIPE_DESC.BCJ_CD2 = "神秘的画家"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_CD2 = "神秘的画家"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_CD2 = "哇！金色传说！"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_CD2 = "NN老师，贴贴~。"

STRINGS.NAMES.BCJ_YM = "永眠"
STRINGS.RECIPE_DESC.BCJ_YM = "永别……"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BCJ_YM = "zzz……"
STRINGS.CHARACTERS.BCJ.DESCRIBE.BCJ_YM = "如果现实是场噩梦，能否选择长眠不醒？"
STRINGS.CHARACTERS.GYC.DESCRIBE.BCJ_YM = "如果选择长眠不醒，梦中能否与我同存？"

STRINGS.NAMES.GYC_FC = "拂尘"
STRINGS.RECIPE_DESC.GYC_FC = "拂尘……"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GYC_FC = "像是仪式用品。"
STRINGS.CHARACTERS.BCJ.DESCRIBE.GYC_FC = "手痒，想揪，拦不住的."
STRINGS.CHARACTERS.GYC.DESCRIBE.GYC_FC = "极端情况下可以扫地."

STRINGS.NAMES.MY_CD = "魔女"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MY_CD = "台词1。"  --路人检查台词
STRINGS.CHARACTERS.BCJ.DESCRIBE.GMY_CD = "台词2." --小白检查台词
STRINGS.CHARACTERS.GYC.DESCRIBE.MY_CD = "台词3."  --道士检查台词

STRINGS.NAMES.MY_CD_DWQ = "定位器"  --未放置到地上的
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MY_CD_DWQ = "台词1。"  --路人检查台词
STRINGS.CHARACTERS.BCJ.DESCRIBE.GMY_CD_DWQ = "台词2." --小白检查台词
STRINGS.CHARACTERS.GYC.DESCRIBE.MY_CD_DWQ = "台词3."  --道士检查台词

STRINGS.NAMES.MY_CD_DWQ_JZ = "定位器"  --放置到地上的
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MY_CD_DWQ_JZ = "台词1。"  --路人检查台词
STRINGS.CHARACTERS.BCJ.DESCRIBE.GMY_CD_DWQ_JZ = "台词2." --小白检查台词
STRINGS.CHARACTERS.GYC.DESCRIBE.MY_CD_DWQ_JZ = "台词3."  --道士检查台词

STRINGS.BCJ_CD1_SPEECH = {
	"台词1",
	"台词2",
	"台词3",
	"台词4",
	"台词5",
	"台词6",
	"台词7",
	"台词8",
	"台词9",
	"台词10", 
}

STRINGS.BCJ_CD2_SPEECH = {
	"台词1",
	"台词2",
	"台词3",
	"台词4",
	"台词5",
	"台词6", 
}